export const TOKEN_KEY = 'accessToken'
export const CLIENT_ID = 'sample-client-id'
export const CLIENT_SECRET = 'sample-client-secret'
export const AUTH_API_VERSION = 'v1.0'
export const AUTH_SCOPE = 'is-05'
export const AUTH_GRANT = 'password'
